---
title: "Data Exploration of Grupo Bimbo Data Set"
author: "Keith Hultman"
date: "June 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
```
# Load Data

```{r}
setwd("/Volumes/Half_Dome/datasets/grupo-bimbo/")
load("train2.Rdata")
```

## Is current human model under estimating demand?

```{r}
explore <- mutate(train2, has_return = (returns_units > 0))

# Create lag and lead sales data - shows the 'supply' to stores
explore <- explore %>% 
  group_by(product, client, depot) %>%
  arrange(week) %>% 
  mutate(sales_delta = sales_units - lag(sales_units), 
         sales_lead_delta = lead(sales_units) - sales_units,
         demand_delta = demand - lag(demand),
         demand_lead_delta = lead(demand) - demand,
         had_return = lag(has_return))

explore$had_return <- as.logical(explore$had_return)
explore[is.na(explore)] <- 0

summary(explore$sales_lead_delta)

sum(explore$has_return) 
sum(explore$has_return) / length(explore$has_return)
 
save(explore, file = "explore.Rdata")
load("explore.Rdata")
set.seed(0928645)
sampled <- sample_frac(explore, 0.1, replace = FALSE)
save(sampled, file = "sampled_returns.Rdata")
```

```{r}
load("sampled_returns.Rdata")

ggplot(sampled, aes(x=had_return, y= sales_delta)) + geom_boxplot() 
ggplot(sampled, aes(x=had_return, y= returns_units)) + geom_boxplot()
median(sampled$returns_units[sampled$has_return == TRUE])
median(sampled$returns_units[sampled$had_return == TRUE])
median(sampled$returns_units[sampled$had_return == FALSE])

ggplot(sampled, aes(log(returns_units), sales_lead_delta)) + 
  geom_point() + 
  stat_smooth() +
  ggtitle("Effect of number of returns from previous week on following weeks sales") +
  ylab("Change in Sales") +
  xlab("Number of units returned (Log scale)") 

ggplot(sampled, aes(x=had_return, y= demand)) + geom_boxplot()

ggplot(sampled, aes(log(returns_units), demand_lead_delta)) + 
  geom_point() + 
  stat_smooth() +
  ggtitle("Effect of number of returns from previous week on following weeks demand") +
  ylab("Demand") +
  xlab("Number of units returned (Log scale)")


#ggplot(explore, aes(returns_units, sales_lead_delta)) + geom_point() + stat_smooth()
```

This is for Tech report

```{r Responsiveness of Human model, echo=FALSE, message=TRUE, warning=FALSE}
setwd("/Volumes/Half_Dome/datasets/grupo-bimbo/")
load("sampled_returns.Rdata")

plot1 <- ggplot(sampled, aes(x=has_return, y= sales_lead_delta)) + 
  geom_boxplot() + 
  ggtitle("A) Comparison of product with and \n without returns on following \n week's supply") +
  ylab("Change in Sales (week x+1 - week x)") +
  xlab("Previous week had return")

plot2 <- ggplot(sampled, aes(log(returns_units), sales_lead_delta)) + 
  geom_point() + 
  stat_smooth() +
  ggtitle("B) Effect of number of returns from \n previous week on following \n weeks supply") +
  ylab("Change in Sales") +
  xlab("Number of units returned \n in previous week (Log scale)")

plot3 <- ggplot(sampled, aes(x=had_return, y= demand)) + 
  geom_boxplot() + 
  ggtitle("C) Comparison of product with and \n without returns on following \n week's demand") +
  ylab("Change in Demand") +
  xlab("Previous week had return")

plot4 <- ggplot(sampled, aes(log(returns_units), demand_lead_delta)) + 
  geom_point() + 
  stat_smooth() +
  ggtitle("D) Effect of number of returns from \n previous week on following \n weeks demand") +
  ylab("Change in Demand") +
  xlab("Number of units returned \n in previous week (Log scale)")

multiplot(plot1, plot2, plot3, plot4, cols=2)

setwd("~/github/grupo-bimbo/Final/")
```



