---
title: "data_exploration"
author: "Keith Hultman"
date: "June 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(data.table)
library(feather)
library(ggplot2)
```
# Load Data

```{r}
setwd("/Volumes/Half_Dome/datasets/grupo-bimbo/")
load("train1.Rdata")
load("train2.Rdata")
load("validate.Rdata")
load("test.Rdata")
load("clients.Rdata")
load("products.Rdata")


```

# Products missing in the train set that are in the kaggle test set
The kaggle page mentioned products in the test set that were not in the train set
```{r}

train1_products <- unique(train1$product)

test_products <- unique(test$product)

#Train products missing from test products
train1_products[!(train1_products %in% test_products)]

# Test products missing from train products
new_products <- as.data.frame(test_products[!(test_products %in% train1_products)])
colnames(new_products) <- c("product")

new_products <- new_products %>%
  left_join(products, by = "product")

```

# Are there any products missing in train2 that are in validate test set?

```{r}

validate_products <- unique(validate$product)
train2_products <- unique(train2$product)


#Train2 products missing from validate products
train2_products[!(train2_products %in% validate_products)]

# Validate products missing from train2 products
new_validate_products <- as.data.frame(validate_products[!(validate_products %in% train2_products)])
colnames(new_validate_products) <- c("product")

new_validate_products <- new_validate_products %>%
  left_join(products, by = "product")

new_validate_products 

# Number of products in our validate test set that are not in our train2 data. We will need to have a naive model for new products. 
nrow(new_validate_products)
```



# Summarize Data

```{r}
# train
train
# test
test
# clients file
clients
# products file
products
# town_state file
town_state

# Weeks in training data set and number of samples per week
train %>% 
  group_by(week) %>%
  summarise(Number = n())

# Weeks and samples in the test set
test %>%
  group_by(week) %>%
  summarise(Number = n())

# Unique Agencia
train1 %>% summarise(n_distinct(depot))
# Unique Canal
train1 %>% summarise(n_distinct(channel))
# Unique Ruta
train1 %>% summarise(n_distinct(route))


```

## From now on, only look at Train2 data set

```{r Some Visualizations}
load("train2.Rdata")

set.seed(65)
product_sample <- products %>% 
  sample_n(15)
product_sample

# Scatterplot of sample products
train2 %>% 
  filter(product %in% product_sample$product) %>%
  ggplot(aes(x = week, y = demand)) +
  geom_point() +
  facet_wrap(~ product, scale = "free_y")

# Trend lines of average demand over time for sample products
product_trend_sample <- train2 %>% 
  filter(product %in% product_sample$product) %>%
  group_by(product, week) %>%
  summarise(ave_demand = mean(demand))
  
product_trend_sample  

ggplot(product_trend_sample, aes(x = week, y = ave_demand)) +
  geom_point() +
  stat_smooth() +
  facet_wrap(~ product, scale = "free_y")



```

