---
title: "Forecasting"
author: "Keith Hultman"
date: "June 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(zoo)
```

```{r Examine one sample of time series}
setwd("/Volumes/Half_Dome/datasets/grupo-bimbo/")
load("train2.Rdata")

example <- train2 %>% 
  filter(product == 5710) %>%
  filter(client == 48572)

example
# note that this is missing week 5 data
example$demand

# put demand into time series. 
example.ts <- ts(example$demand, start = 3, end = 7, frequency = 1)
example.ts
# if we don't fill in that missing data, then the time series will start over from the first observation



week5 <- data.frame(week=5, depot="1355", channel="2", route="1606", client="48572", product="5710", sales_units= 0, sales= 0, returns_units= 0, returns= 0, demand=0)

example_complete <- example %>%
  bind_rows(week5) %>%
  arrange(week)

example_complete
example.ts <- ts(example_complete$demand, start = 3, end = 7, frequency = 1)
#example.ts <- ts(c(100, 200, 300, 400, 500), start = 3, end = 7, frequency = 1)
?ts
?arima

example.arima <- arima(example.ts, order = c(3,0,0))
str(example.arima)

example.predict <- predict(example.arima, n.ahead=2)
example.predict
example.predict$pred
ts.plot(example.ts, example.predict$pred, lty=1:2)
```

Create time series for each product and client. 

```{r}
load("products.Rdata")
load("clients.Rdata")
  
# Test with a sample - switch to numeric for filter 
train2$product <- as.numeric(train2$product)
train2$client <- as.numeric(train2$client)
product_client_sample <- train2 %>%
  filter(product < 300, client < 1000)

# Group data by product/client/week and then take the median for those values (includes multiple depots)
product_client_sample <- product_client_sample %>%
  group_by(product, client, week) %>%
  summarise(p_c_w = median(demand))
product_client_sample

# Spread out the data to columns (shows all weeks of data, missing is NA)
product_client_sample2 <- spread(product_client_sample, week, p_c_w)

# Set NAs to a constant (tried 0, and 1)
product_client_sample2[is.na(product_client_sample2)] <- 1

# Put back into rows
product_client_sample2 <- gather(product_client_sample2, "week", "demand", 3:7)
```

Linear model for each product/client

```{r}
product_client_sample2 <- product_client_sample2 %>% 
  group_by(product, client) %>%
  do(linearmodel = lm(demand ~ week, data = .))

summary(product_client_sample2$linearmodel[2])

```


Time Series and Arima
```{r}
# Create column of time series
product_client_sample2.ts <- product_client_sample2 %>% 
  group_by(product, client) %>%
  arrange(week) %>%
  do(timeseries = ts(.$demand, start = 3, end = 7, frequency = 1)) 

product_client_sample2.ts
unlist(product_client_sample2.ts$timeseries[5])

# Now I have a time series object for each client/product combination. 

# Below is where I am having trouble

product_client_sample2.ts$arima1 <- lapply(product_client_sample2.ts$timeseries, FUN =
                                             arima, order = c(3,0,0))



product_client_sample2.ts <- product_client_sample2.ts %>%
  do(arima1 = arima(.$timeseries, order = c(1,0,0)))

```

