---
title: "Moving Average"
author: "Keith Hultman"
date: "June 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Volumes/Half_Dome/datasets/grupo-bimbo/")
load("train2.Rdata")
load("validate.Rdata")

# To run on full train/test set
#load("train1.Rdata")
# load("test.Rdata")
#train2 <- train1
#validate <- test



validate$sales_units <- NULL
validate$sales <- NULL
validate$returns <- NULL
validate$returns_units <- NULL
validate$channel <- NULL
validate$route <- NULL
```

# Average Demand model
This model predicts that the demand for a product is the median demand for each client and product. If the client product median is not available, it will use the product median demand. If the product median is not available it will use the overall median demand. 

```{r}
# Find the overall median demand
overall <- median(train2$demand)
overall


# Product median demand
product <- train2 %>%
  group_by(product) %>%
  summarise(p_d = median(demand))

product

# Product/Client median demand
product_client <- train2 %>%
  group_by(product, client) %>%
  summarise(p_c_d = median(demand))

product_client

# Product/Client/Depot median demand
product_client_depot <- train2 %>%
  group_by(product, client, depot) %>%
  summarise(p_c_d_d = median(demand))

save(product_client, file = "product_client.Rdata")
save(product_client_depot, file = "product_client_depot.Rdata")
load("product_client.RData")
product_client
validate

medians <- left_join(validate, product_client_depot, by = c("product", "client", "depot"))

medians <- left_join(medians, product_client, by = c("product", "client"))

medians <- left_join(medians, product, by = "product")


medians$pred <- medians$p_c_d
medians$pred[is.na(medians$pred)] <- medians$p_d[is.na(medians$pred)]
medians$pred[is.na(medians$pred)] <- overall
medians$pred <- round(medians$pred, 0)

# With Depot specificity
medians$pred2 <- medians$p_c_d_d
medians$pred2[is.na(medians$pred2)] <- medians$p_c_d[is.na(medians$pred2)]
medians$pred2[is.na(medians$pred2)] <- medians$p_d[is.na(medians$pred2)]
medians$pred2[is.na(medians$pred2)] <- overall
medians$pred2 <- round(medians$pred2, 0)

test_medians_pc <- medians %>% select(id, pred) %>% arrange(id)
colnames(test_medians_pc) <- c("id", "Demanda_uni_equil")
write.csv(test_medians_pc, file = "test_medians_pc.csv", row.names = FALSE)
test_medians_pcd <- medians %>% select(id, pred2) %>% arrange(id)
colnames(test_medians_pcd) <- c("id", "Demanda_uni_equil")
write.csv(test_medians_pcd, file = "test_medians_pcd.csv", row.names = FALSE)
save(medians, file = "medians.Rdata")

```


Evaluation

```{r RMSLE}

RMSLE <- function(prediction, actual){
  sqerror <- (log(prediction + 1) - log(actual + 1))^2
  epsilon <- sqrt(sum(sqerror) / length(sqerror))
  return(epsilon)
}


```

```{r}
RMSLE(medians$pred, medians$demand)
RMSLE(medians$pred2, medians$demand)
```


