---
title: "Grupo Bimbo Exploration"
author: "Renjith Madhavan"
date: "June 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("feather", type = 'source')
#install.packages("data.table")
#library(feather)
#install.packages("dplyr")
library(data.table)
library(dplyr)
```

## Loading Data for Grupo Bimbo

The first step in doing the analysis would be to load the data into R. For this I am using data.table package from CRAN. 

```{r}
setwd("D:/r/wd/bimbo")
train <- fread("data/source/train.csv", header = TRUE, colClasses = c(Cliente_ID="numeric",Producto_ID="numeric",Demanda_uni_equil="numeric"), col.names = c("week", "depot", "channel", "route", "client", "product", "sales_units", "sales", "returns_units", "returns", "demand"))
#train <- fread("C:/renjith/datascience/git/data/grupobimbo/train.csv", header = TRUE)
train <- tbl_df(train)
test <- fread("data/source/test.csv", header = TRUE)
#test <- fread("C:/renjith/datascience/git/data/grupobimbo/test.csv", header = TRUE)
test <- tbl_df(test)
clients <- tbl_df(read.csv("data/source/cliente_tabla.csv"))
products <- tbl_df(read.csv("data/source/producto_tabla.csv"))
town_state <- tbl_df(read.csv("data/source/town_state.csv"))

colnames(train) <- c("week", "depot", "channel", "route", "client", "product", "sales_units", "sales", "returns_units", "returns", "demand")
colnames(test) <- c("id", "week", "depot", "channel", "route", "client", "product")
colnames(clients) <- c("client", "client_name")
colnames(products) <- c("product", "product_name")
colnames(town_state) <- c("depot", "town", "state")

# train$depot <- as.factor(train$depot)
# train$channel <- as.factor(train$channel)
# train$client <- as.factor(train$client)
# train$product <- as.factor(train$product)
# train$route <- as.factor(train$route)

# town_state$depot <- as.factor(town_state$depot)

train2 <- train %>% filter(week <= 7)
validate <- train %>% filter(week > 7)

train2 %>% 
  group_by(week) %>%
  summarise(Number = n())

validate %>% 
  group_by(week) %>%
  summarise(Number = n())

save(train, file = "data/rdf/renjith/train.Rdata")
save(train2, file = "data/rdf/renjith/train2.Rdata")
save(validate, file = "data/rdf/renjith/validate.Rdata")
save(test, file = "data/rdf/renjith/test.Rdata")
save(clients, file = "data/rdf/renjith/clients.Rdata")
save(products, file = "data/rdf/renjith/products.Rdata")
save(town_state, file = "data/rdf/renjith/town_state.Rdata")






# Exploring using dplyr
d1 <- tbl_df(train_dt)
d1
glimpse(train_dt)
glimpse(product_table)
d1 %>%
  summarise(total_records = n(),
            n_weeks = n_distinct(week))

d1 %>%
  group_by(week) %>%
  summarise(total_sales_units = sum(sales_units),
            max_returns = max(returns_units),
            total_return_units = sum(returns_units),
            unique_prdts = n_distinct(product)) %>%
  arrange(week)
train_dt[returns_units == 250000]
product_table[Producto_ID == 3509]
#create data table for weeks 3,4,5,6 and 7
train_wk34567 <- train_dt[week %in% c(3,4,5,6,7)]

#create data table for 8 and 9
train_wk89 <- train_dt[week %in% c(8,9)]

```

## Including Plots
